spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+
  servlet:
    multipart:
      max-file-size: 200MB
server:
  port: 3344
  servlet:
    context-path: /car

mybatis:
  type-aliases-package: com.mxp.car.model
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 60000